"""add users table

Revision ID: 51e93d39ed03
Revises: bb327748b3f1
Create Date: 2026-08-05 14:42:18.287911

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51e93d39ed03"
down_revision = "bb327748b3f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
