"""create students courses and student_courses tables

Revision ID: bb327748b3f1
Revises:
Create Date: 2026-08-04 21:34:39.857418

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb327748b3f1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "students",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("grades", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("student_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "student_courses",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.student_id"],
        ),
        sa.PrimaryKeyConstraint("student_id", "course_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_courses")
    op.drop_table("students")
    op.drop_table("courses")
    # ### end Alembic commands ###
